== La Vida de Elizabeth Ashbridge

Como mi vida ha estado llena de muchos sucesos poco comunes,
he considerado apropiado hacer algunas observaciones
de los tratos de la Divina Bondad conmigo.
A menudo, he tenido motivos para decir junto con David:
"`bueno es para mí ser afligido;`"^
footnote:[Salmo 119:71 LBLA]
y deseo fervientemente que los que lean las siguientes líneas tengan cuidado,
y huyan de los males en los que me he visto envuelta.

Nací en Middlewich, en Cheshire, en el año 1713, de padres honestos,
llamados Thomas y Mary Sampson.
Mi padre tenía un buen carácter, pero no era tan estricto en la religión como mi mamá,
quien era un modelo de virtud para mí. Fui la única hija de mi padre,
pero mi mamá tenía un hijo y una hija de un matrimonio anterior.
Poco después de mi nacimiento, mi padre se dedicó a la vida marítima,
y al continuar con su profesión (que era la de médico) hizo muchos viajes largos.
Continuó con su vida de marinero hasta que cumplí los doce años,
así que el cuidado de la primera parte de mi educación fue delegado a mi mamá;
y ella cumplió con su deber al esforzarse en impregnar
en mi mente los principios de la virtud.
Tengo motivos para estar agradecida por haber sido bendecida con una madre así;
sus buenos consejos y advertencias hacia mí han sido como el "`pan sobre las aguas`"^
footnote:[Eclesiastés 11:1]
que regresó después de muchos días. Ella era un ejemplo
de instrucción para todos los que la conocían,
y era muy amada por todos.
Pero, ¡ay! al llegar el momento en que podía esperar recibir algún
fruto de sus esfuerzos y encontrar consuelo en mí,
la abandoné.

En mi infancia,
tenía una profunda consideración por la religión y por la gente religiosa,
especialmente por los ministros, a quienes consideraba hombres buenos y amados de Dios,
deseando fervientemente que ese fuera también mi caso.
También sentía una gran ternura por los pobres,
recordando haber leído que ellos eran los "`amados del Señor.`" Yo suponía
que esto se refería a los que eran pobres en las cosas temporales,
y entonces a menudo los visitaba en sus casitas,
y solía pensar que estaban en una condición mejor que la mía. Y si tenía dinero,
o cualquier cosa para regalar, se los daba,
recordando que los que se apiadaban de los pobres le prestaban
al Señor. Reprendía a los que fingían superficialmente la religión;
y cuando escuchaba a las personas decir palabrotas, me angustiaba;
porque mi madre me había dicho que si usaba alguna palabra grosera, Dios no me amaría.

Noté que había sociedades religiosas diferentes.
Pensaba a menudo en esto y lloraba,
con deseo de ser dirigida a la que fuera la más adecuada
para mí. Bajo este estado de mente pasé mis años de juventud.
Algunas veces cometía los errores que eran comunes entre los niños,
pero siempre me arrepentía de lo que había hecho mal;
y hasta los catorce años era tan inocente como la mayoría de los niños. Pero por esta
época comenzaron mis angustias (que se han extendido durante la mayor parte de mi vida),
al ceder ante un insensato deseo de encariñarme con un joven,
que sin el consentimiento de mis padres, me cortejó hasta que accedí a casarme con él;
y después--lo cuento con dolor de corazón--me permití dejarme llevar por la noche,
y nos casamos.
Mis padres hicieron todo lo posible por buscarme en cuanto desaparecí, pero fue en vano.

Este acto precipitado me sumergió en una gran tristeza.
Rápidamente me invadió la culpa por haber dejado a mis padres,
quienes tenían el derecho de ser consultados ante tal acontecimiento.
Pero pronto fui castigada por mi desobediencia y convencida de mi error,
porque en tan sólo cinco meses fui despojada del amor de mi corazón,
y quedé viuda y desconsolada siendo aún tan joven; y así, me quedé sin hogar.
Mi esposo se ganaba la vida en su oficio, que era tejedor de medias;
y mi padre estaba tan disgustado por mi comportamiento,
que no quiso hacer nada para ayudarme.
Mi querida madre sentía cierta compasión por mí y me ubicó entre sus vecinos.
Más adelante, siguiendo su consejo,
me fui a vivir con un familiar de ella en Dublín. Esperábamos
que mi ausencia suavizara el rigor de mi padre,
pero continuó inflexible.
No quiso mandar a llamarme para que regresara,
y yo no me atrevía a volver a menos que él quisiera.

El pariente donde me fui a vivir era uno del pueblo llamado Cuáquero.
Sus costumbres eran tan diferentes de las que yo estaba acostumbrada,
que la visita me resultó muy desagradable.
Había sido criada en la forma de la iglesia de Inglaterra, y aunque, como dije,
tenía una formación religiosa, aun así se me permitía cantar y bailar,
cosa que mi primo no permitía. La gran jovialidad de mi temperamento natural
no me permitía ceder al sombrío sentido de la aflicción y convicción,
y por tanto, mis restricciones en aquel tiempo tuvieron un efecto negativo,
porque me volví más desenfrenada y arrogante que nunca.
Mi primo me reprendía frecuentemente,
pero en ese entonces pensaba que su conducta provenía de un deseo de verse diferente,
y yo no quería que me controlaran.
Como tenía un pariente lejano en el lado oeste de Irlanda,
me fui a vivir con él. Ahí gocé de toda la libertad que podía desear;
pues eso que le parecía desagradable para mi otro pariente,
era bastante agradable para este.
Entre estos dos familiares pasé los siguientes tres años y tres meses.

Mientras estaba en Irlanda, me involucré en una íntima amistad con una viuda y su hija,
quienes eran católicas romanas.
Hablábamos con frecuencia sobre religión,
cada una de nosotras defendiendo sus principios específicos;
y aunque yo era muy dada a la vanidad,
nuestras discusiones a menudo me hacían reflexionar.
La anciana me contaba de los poderosos milagros hechos por los sacerdotes católicos,
y entonces, mis propias creencias comenzaron a ser sacudidas,
y llegué a pensar que si estas cosas eran así,
ellos debían ser realmente los sucesores de los apóstoles.
Ella percibió el estado de mi mente, y un día exclamó con exaltación: "`¡Oh,
si yo pudiera ser el feliz instrumento para convertirte a la santa fe católica,
todos los pecados que he cometido serían perdonados!`"

Algunas veces asistía a su lugar de adoración,
pero ninguno de mis conocidos sabía mi motivo.
El asunto llegó tan lejos, que un sacerdote llegó a conversar conmigo.
Como era joven y mi juicio débil, estaba dispuesta a creer lo que me dijera;
y sin embargo, decidí no adoptar ciegamente su credo.
Pensé que si sus principios de fe eran sólidos,
no se opondrían a que yo conociera cuáles eran; por lo tanto,
cuando volví a ver al sacerdote,
le dije que tenía cierta intención de convertirme en una de su rebaño,
pero que primeramente deseaba conocer a qué tenía que acceder.
Él respondió que primero debía confesarle mis pecados,
y me dio hasta el día siguiente para considerarlos.
No me opuse a esto,
consciente de no haber hecho nada por lo que alguien pudiera perjudicarme;
y pensando que si lo que él había dicho era cierto, la confesión sería para mi beneficio.
Cuando regresó, le dije todo lo que podía recordar, lo cual, por mi parte,
me pareció bastante malo;
pero él dijo que me consideraba la criatura más inocente
que jamás le hubiera hecho una confesión. Cuando terminé,
él tomó un libro y leyó de él, y me dijo que si me iba a unir a ellos,
debía jurar creer en esas cosas.
No molestaré al lector con el relato de su ridículo contenido.
Lo que particularmente me hizo dudar en mi nueva intención,
fue que debía jurar que el Pretendiente,^
footnote:[Jacobo Carlos Estuardo, conocido como el Viejo Pretendiente,
era el hijo Católico del depuesto Rey Jacobo II,
quien pretendía ser el legítimo heredero de los tronos Inglés y Escocés,
y realizó varios intentos para tomar la corona de Guillermo y María,
y más tarde de la Reina Ana.]
el hijo del rey Jacobo, era el verdadero heredero de la corona de Inglaterra;
y que todos los que murieran fuera de la iglesia romana serían condenados.
Estas doctrinas me dejaron perpleja.
Dudé y pedí tiempo para considerarlas; pero antes de volver a ver al sacerdote,
un cambio de circunstancias me libró de tener que brindarle una respuesta.

Mi padre seguía manteniéndome tan lejos, que me sentía totalmente excluida de su cariño,
y por tanto decidí no regresar a casa.
Conocí a una dama,
que recién había llegado de Pennsylvania y que tenía la intención de regresar,
y como tenía un tío (hermano de mi mamá) en ese lugar,
en seguida acordé con ella mi pasaje.
Yo desconocía la naturaleza de un contrato por servidumbre,^
footnote:[Un contrato por servidumbre es una forma de trabajo,
en la que una persona firma un acuerdo obligatorio para
trabajar sin salario por un número determinado de años,
a cambio del pago de una deuda o el costo del transporte trasatlántico.]
y me dejé comprometer.
Esto se hizo en secreto para que no se descubriera.
Tan pronto como firmé el contrato, ella me invitó a ver el barco en que iba a navegar.
Acepté de inmediato y subimos a bordo, donde había otra joven dama, quien,
como descubrí más adelante,
era de una familia respetable y había sido llevada allí de la misma manera que yo.
Me agradó pensar que iba a tener una compañera tan agradable en mi viaje.
Mientras estábamos ocupadas conversando, mi guía tenía la intención de ir a tierra,
y cuando deseé bajar, me lo impidieron.
Entonces me di cuenta de que había sido secuestrada.
Me mantuvieron prisionera en el barco por tres semanas,
al cabo de las cuales mi compañera fue encontrada
por algunos de sus amigos que la sacaron de allí;
y gracias a la información que brindó, mis amigos mandaron a llamar al oficial de aguas,^
footnote:[Es un funcionario de la ley encargado de vigilar las masas de agua.]
que me llevó a la orilla.
Me mantuvieron bajo custodia por dos semanas,
pero al final encontré los medios para escapar.

Sin embargo, tenía tantos deseos de ir a América que no quería renunciar a ese plan,
y al encontrar al capitán, le pregunté cuándo zarpaba; me lo hizo saber y subí a bordo.
Había en el barco sesenta sirvientes irlandeses y varios pasajeros ingleses.
Los ingleses no estaban familiarizados con el idioma irlandés,
que yo me había esforzado mucho por aprender y entendía muy bien.
Veinte de los sirvientes irlandeses le pertenecían a la dama que mencioné anteriormente,
quien, junto con un joven, hermano de su esposo, iba con nosotros.
Mientras estábamos en la costa de Irlanda, donde el viento nos detuvo por unas semanas,
escuché a los irlandeses ideando cómo podrían liberarse cuando llegaran a América.
Para llevar a cabo su plan,
decidieron que se rebelarían y matarían a la tripulación del barco y a todos los ingleses,
y que designarían al joven que mencioné para que navegara
la embarcación. Pero al escuchar su conversación,
divulgué su criminal intención al capitán, quien se lo hizo saber a los ingleses.
Al siguiente día nos dirigimos a la costa,
pero cuando nos encontrábamos cerca de la caleta de Cork, bajamos velas y anclamos,
bajo el pretexto de que el viento no nos permitía continuar nuestro curso.
Se izó la pequeña embarcación y se invitó a los pasajeros a ir y divertirse en la costa.
Junto con unos cuantos,
el líder de la banda de los sirvientes irlandeses se fue a la orilla.
Esto era todo lo que se deseaba.
Los otros lo dejaron en la orilla y regresaron al barco.
El capitán entonces les ordenó inmediatamente a sus
hombres que levaran anclas e izaran velas.
Hubo una gran conmoción entre los irlandeses porque
se iba a dejar al joven líder en tierra,
pero el capitán les dijo que el viento había cambiado de
dirección y que no se quedaría ni por su propio hijo.
Así se frustraron los planes malvados de los irlandeses,
de forma que ellos no sospecharon.
Y se consideró conveniente mantener todo en secreto,
para que no se dieran cuenta de mi involucramiento y me perjudicaran.
Sin embargo, al final descubrieron que yo entendía su idioma,
porque sonreí por una historia que estaban contando.
Y desde ese momento idearon muchas maneras para hacerme daño,
por lo que varios de ellos fueron castigados.

El 15 del séptimo mes, que era nueve semanas después de que partimos de Dublín,
llegamos a Nueva York.
Aquí fui traicionada por los mismos hombres cuyas vidas había salvado.
El capitán encargó que se hiciera un contrato por servidumbre,
y me amenazó con la cárcel si yo me rehusaba a firmarlo.
Yo le dije que podía encontrar los medios para pagarle el costo de mi pasaje,
sin tener que quedar atada.
Pero respondió que yo debía escoger entre firmar el contrato que me había mostrado,
o que el anterior que había firmado en Irlanda entraría en vigor.
En gran temor firmé el que me ofrecía;
porque para entonces había descubierto el carácter de la mujer que me
había inducido por primera vez a considerar la posibilidad de ir a América.
Ella era una vil criatura, y temía que si caía en sus manos sería tratada muy mal.

Después de dos semanas fui vendida como sirvienta.
Al inicio no tenía muchas razones para quejarme del trato que recibía;
pero después de un corto tiempo surgió un problema, del que yo era inocente,
y que dispuso a mi amo en mi contra, haciendo que me tratara inhumanamente.
Sería imposible para mí transmitir una idea exacta de los sufrimientos de mi servidumbre.
Aunque mi padre no era un hombre rico, aun así, vivía bien en su casa,
y me había acostumbrado a hacer poco trabajo además de mis deberes escolares;
pero entonces me di cuenta de que hubiera sido mejor
para mí si me hubieran criado con menos indulgencia.
No me permitían usar ropa decente;
estaba obligada a realizar los trabajos pesados más bajos,
e incluso a caminar descalza en la nieve.
Sufrí las mayores dificultades que mi cuerpo era capaz de soportar,
y el impacto que se produjo en mi mente fue casi mi destrucción absoluta.

Mi amo parecía ser una persona muy religiosa,
que tomaba el sacramento (así llamado) regularmente, y oraba cada noche con su familia,
a menos que no pudiera encontrar su libro de oraciones; pues, según mi conocimiento,
nunca oraba sin él. Su ejemplo, sin embargo, me hacía sentir repulsión por su religión;
porque aunque yo misma tenía muy poco de religión,
tenía alguna idea de lo que debían ser las personas religiosas.
Con respecto a la religión, mis opiniones comenzaron a fluctuar;
incluso dudé de la existencia de tal cosa,
y comencé a pensar que las convicciones que había sentido desde mi infancia eran sólo
los prejuicios de mi educación. Estas convicciones parecían entonces haberse perdido,
y por algunos meses no recuerdo haberlas sentido.
Mi corazón se endureció y estaba lista a concluir la inexistencia de Dios.
La veneración que había sentido en mi infancia por los hombres religiosos se había perdido;
ahora los veía de una manera muy diferente.
La casa de mi amo era un lugar común de descanso para el clero,
y algunas veces los que venían desde lejos se alojaban donde él. Lo que
noté en el comportamiento de estos hombres confirmaron mis opiniones ateas.
Ellos se entretenían por las noches jugando a las cartas y cantando,
y momentos después elevaban oraciones y cantaban salmos al Dios Todopoderoso.
A menudo decía para mí: "`Si hay un Dios, debe ser un Ser puro,
y no escuchará las oraciones de tales labios corruptos.`"

Pero Aquel que de manera abundante me ha mostrado misericordia--como se verá más adelante--no
permitió que mi mente se desconcertara por mucho tiempo con tales dudas;
pues en un momento, cuando mis pies estaban al borde del pozo sin fondo, Él me rescató.

A una mujer, y a nadie más,
le comenté la naturaleza del problema que había ocurrido
dos años antes entre mi amo y yo.
Él se enteró de esto por medio de ella, y aunque sabía que lo que yo decía era verdad,
mandó a llamar al azotador del pueblo para que me corrigiera.
Me mandaron a llamar.
Mi amo nunca me preguntó si había dicho tal cosa,
sino que simplemente ordenó que me desvistiera.
Mi corazón estaba a punto de estallar.
Hubiera estado dispuesta a renunciar a mi vida antes que sufrir tal desgracia.
"`Si existe un Dios,`" dije,
"`ten compasión en mirar a una de Tus más infelices criaturas y defiende mi causa;
porque Tú sabes que lo que he dicho es la verdad;`" y si no hubiera
sido por un principio más noble del que era capaz mi amo,
se lo hubiera hecho saber a su esposa.
Luego, fijando mi mirada en mi cruel amo, le dije: "`Señor, si no tiene piedad de mí,
por el bien de mi padre líbrame de esta vergüenza;`" (pues
él había oído de mis padres por muchas otras personas),
"`y si cree que merezco tal castigo, entonces hágalo usted mismo.`"
Se paseó de un lado a otro en la habitación,
y luego le dijo al azotador que se fuera y volviera a lo suyo.
Así me libré de ser golpeada; pero mi carácter sin embargo parecía estar perdido.
Se dijeron muchas noticias de mí, que gracias a Dios no eran ciertas,
pero sufrí tanta crueldad que no la podía soportar;
y estaba tentada a ponerle fin a mi miserable vida.
Le presté atención a esa tentación, y con esa intención me dirigí al ático para ahorcarme.
Fue entonces cuando me convencí de que existía un Dios,
porque en el momento en que entré al lugar, un horror y un temblor se apoderaron de mí;
y mientras permanecía en terrible perplejidad, me pareció escuchar una voz que decía:
"`Hay un infierno más allá de la tumba.`"
Me quedé muy sorprendida y exclamé: "`Oh Dios, ten misericordia,
y permíteme soportar lo que Tú en Tu providencia traigas o permitas que me acontezca.`"
Luego bajé las gradas, pero no le dije a nadie lo que había estado haciendo.

Poco tiempo después de esto tuve un sueño; y aunque algunos desacreditan los sueños,
este me pareció ser muy importante para mí,
y por tanto lo mencionaré. Me pareció oír que llamaban a la puerta, y cuando la abrí,
había una mujer de aspecto piadoso sosteniendo con su mano derecha una lámpara encendida.
Y con un semblante imponente, fijó su mirada sobre mí y me dijo:
"`He sido enviada para decirte, que si te vuelves al Señor tu Dios, quien te ha creado,
tendrá misericordia de ti y tu lámpara no se apagará en la oscuridad.`"
Su lámpara se encendió entonces de manera extraordinaria,
y me dejó. Entonces me desperté.

Pero, ¡ay!
No me rendí a la "`visión celestial,`" como creo que puedo llamarla;
y estuve a punto de ser cautivada en otra trampa y de la más peligrosa índole.
Me consideraban talentosa en el canto y en el baile,
en los cuales me deleitaba grandemente.
Una vez,
al encontrarme con un grupo de actores de teatro que estaban entonces en Nueva York,
se sintieron atraídos hacia mí, según dijeron,
y me invitaron a convertirme en actriz y a formar parte de ellos.
También mencionaron que iban a buscar los medios para liberarme de mi cruel servidumbre,
y que así pudiera vivir como una dama.
La propuesta me agradó y me esmeré en capacitarme para ellos,
aprendiendo sus obras de teatro incluso cuando debería haber estado durmiendo.
Pero tras una seria reflexión,
decidí no dar ese paso al considerar lo que mi padre pensaría si lo hacía,
porque finalmente había perdonado mi desobediencia por haberme casado,
y había mandado a buscarme para que regresara a casa, deseando fervientemente verme.
Sin embargo, mi corazón orgulloso no me permitía regresar en tan baja condición,
y preferí la esclavitud.

Después de haber servido por unos tres años,
logré pagar lo que me quedaba del contrato y luego trabajé en costura,
lo que me ayudó a mantenerme holgadamente.
Pero, ¡ay!, por lo visto no fui lo suficientemente castigada,
porque tras haberme liberado de la cruel esclavitud,
en el transcurso de tan sólo unos pocos meses, entré en otra de por vida,
al casarme con un joven que se enamoró de mí por mi forma de bailar;
un motivo muy pobre para que un hombre elija una esposa, o una mujer un esposo.
Por mi parte, no estaba enamorada de nada de lo que veía en él;
y me pareció inexplicable, que tras haber rechazado varias ofertas,
tanto en este país como en Irlanda, terminara casándome con un hombre que no amaba.

Mi esposo era maestro de escuela.
Unos cuantos días después de habernos casado,
nos fuimos de Nueva York a un lugar llamado Westerly, en Rhode Island,
donde se había comprometido a administrar una escuela.
Con respecto a la religión, era muy parecido a mí, no tenía ninguna;
y cuando se embriagaba, profería las peores blasfemias.
No menciono esto para exponerlo,
sino con el único fin de evidenciar el efecto que tenía sobre mí; porque me vi arruinada,
al estar unida con un hombre que no amaba, y que era un ejemplo nada bueno para mí.

Ambos parecíamos precipitarnos hacia la destrucción cuando concluí,
que si el cielo no me había desamparado, debía cambiar el curso de mi vida.
Dedicarme al Ser Divino y no amar a mi esposo, parecía incongruente.
Así que diariamente deseaba con lágrimas,
que mis sentimientos fueran dirigidos de manera correcta hacia él; y puedo decir,
que en un corto tiempo, mi amor era sincero.
Me propuse cumplir mi deber hacia Dios,
y esperando llegar al conocimiento de Su voluntad por medio de las Escrituras,
las leía con la determinación de seguir sus instrucciones.
Cuánto más leía, más me inquietaba, sobre todo en lo referente al bautismo.
Tenía razones para creer que había sido rociada en mi infancia,
porque cuando tenía trece años, fui "`confirmada`" por el obispo.
Sin embargo, no podía encontrar ningún precedente de esta práctica en la Escritura.
Mientras leía, me topé con el pasaje que dice: "`el que _creyere_ y fuere bautizado,`"^
footnote:[Marcos 16:16] etc.
Aquí noté que ese creer (del que yo no era capaz cuando fui rociada,
siendo una infante) debe ocurrir antes del bautismo.

Conversaba frecuentemente con los Bautistas del Séptimo día que vivían en mi vecindario,
y finalmente, creyendo que era mi verdadero deber,
en el invierno fui bautizada por uno de sus maestros.
No me uní a ellos en el sentido estricto,
aunque comencé a pensar que el séptimo día era el verdadero día de reposo,
y durante un tiempo lo guardé. Mi esposo no se opuso a esto,
pues vio que mi amor hacia él crecía;
y aún entonces no me negaba a cantar o a bailar cuando me lo pedía,
aunque esta forma de entretenimiento no me producía tanta satisfacción como antes.

Mi esposo y yo nos propusimos ir a Inglaterra, y para ello fuimos a Boston,
donde encontramos una embarcación con destino a Liverpool.
Acordamos nuestro pasaje y esperábamos zarpar en el transcurso de dos semanas;
pero durante ese tiempo,
otro caballero contrató la embarcación para que lo
llevara a él y a sus asistentes a Fayal,
y no iba a llevar a ningún otro pasajero.
Como no había ningún otro barco allí cerca que fuera a zarpar,
desistimos de nuestro plan, aunque permanecimos en Boston por varias semanas.
Mi espíritu aún no estaba satisfecho con respecto a la religión. Había reformado
mi conducta y los que me conocían me consideraban una mujer sobria,
sin embargo no estaba complacida, porque esperaba ver los frutos de tal cambio.
Y a pesar de que muchos me consideraban una persona religiosa,
no me atrevía a pensar así de mí misma.
Conversé con gente de todas las denominaciones, según se me presentaba la oportunidad,
y muchos de ellos pensaban que yo era de su creencia.
Sin embargo, no me uní estrictamente a ninguna de ellas,
sino que resolví continuar buscando hasta encontrar la verdadera.
Esto ocurrió a mis veintidós años.

Mientras estábamos en Boston, un día fui a la reunión de los Cuáqueros,
donde escuché hablar a una mujer Amiga, lo cual me sorprendió un poco.
Me habían hablado de mujeres predicadoras, pero nunca las había escuchado;
y la miré con lástima debido a su ignorancia y con desprecio por su práctica,
diciéndome a mí misma: "`Estoy convencida de que eres una tonta,
y si alguna vez me convierto en Cuáquera, cosa que nunca sucederá, no seré predicadora.`"
Así se ocupó mi mente mientras ella hablaba.
Cuando terminó, un hombre se levantó,
al que pude tolerar mucho más. Habló la sana doctrina,
sobre la buena resolución de Josué:
"`Que yo y mi casa serviremos al Señor.`" Después
de sentarse y de permanecer en silencio por un tiempo,
comenzó a orar, lo que fue acompañado de algo tan extraordinario e impactante,
que me sacó las lágrimas.

Mi esposo solía viajar de un lado a otro, lo que me resultaba muy desagradable,
y entonces después de marcharnos de Boston, fuimos a Rhode Island,
y de allí al extremo este de Long Island,
donde fue contratado para administrar una escuela.
Ese lugar estaba mayormente poblado por Presbiterianos y
en seguida me familiaricé con los más serios de entre ellos.
Mi pobreza no fue un obstáculo para ser recibida por personas de la mejor reputación,
con las cuales conversaba con frecuencia, pero entre más me familiarizaba con ellas,
menos me gustaban sus creencias.
Entretanto, muchas tentaciones asaltaban mi mente inestable.
Después de estar un día fuera y regresar a la casa,
observé que los dueños del lugar donde alquilábamos una habitación,
habían dejado un poco de lino en su apartamento, por el cual tenía que pasar.
Al verlo, tuve la tentación de robar un poco para poder hacer hilo.
Entré y tomé un puñado en mi mano,
pero entonces fui herida con tal sentido de arrepentimiento
que lo puse de nuevo en su lugar y dije:
"`Señor, ¡guárdame de una acción tan vil!`"
Pero la tentación de robar se volvió más fuerte que antes,
y llevé el puñado de lino a mi habitación. Cuando llegué,
el horror se apoderó de mí y con lágrimas clamé: "`Oh, Dios de misericordia,
¡ayúdame a abstenerme de esta acción tan vil!`"
Luego puse el lino devuelta en su lugar y experimenté ese placer que solamente
puede ser conocido por los que han resistido una tentación.

Como mi esposo consiguió otro trabajo más al norte de la isla,
cambiamos nuevamente de domicilio.
El lugar de adoración más cercano correspondía a una congregación de la iglesia de Inglaterra,
que en general era la que más me gustaba, y entonces asistía a ella.

Un nuevo ejercicio, de una naturaleza muy particular, me sobrevino.
Ocurrió en el segundo mes.
Estaba yo sentada junto al fuego en compañía de muchos otros,
entre los que estaba mi esposo, cuando de repente sonó un trueno y un ruido tan fuerte,
como el de una poderosa trompeta, que atravesó mis oídos con estas palabras: "`¡Oh,
la eternidad! ¡La eternidad, el infinito término de la extensa eternidad!`"
Quedé sumamente perpleja, y mientras estaba sentada como en trance,
contemplé algo como un largo pergamino escrito en letras negras,
y al mismo tiempo escuché una voz que decía: "`Estos son tus pecados,
y la sangre de Cristo no es suficiente para lavarlos.
Esto te ha sido mostrado para que confieses que tu condena es justa,
y no para que seas perdonada.`"
Me quedé sentada por un tiempo sin decir una sola palabra,
y finalmente me levanté temblando y me tendí en la cama.
Los que me acompañaban pensaron que mi indisposición
procedía del susto ocasionado por el trueno;
pero provenía de otra fuente.

Durante varios meses después de esto, estuve en un estado casi de desesperación,
y si en algún momento me esforzaba por albergar una
esperanza o aferrarme a alguna promesa de gracia,
el tentador insinuaba que ya era muy tarde para eso;
que el día de misericordia había terminado,
y que sólo aumentaría mis pecados si oraba pidiendo perdón,
y provocaría que la Divina venganza hiciera de mí un monumento de ira.
Me encontraba, por así decirlo, atormentada.
No podía dormir y comía muy poco.
Me volví extremadamente melancólica y no encontraba deleite en nada.
De haber tenido todo el mundo a mi disposición,
lo habría entregado con gusto por un solo vislumbre de esperanza.

Mi esposo estaba impactado al verme tan cambiada.
Yo, que antes lo había entretenido con el canto y el baile,
en lo que él se deleitaba bastante,
no podía hacerlo más. Mi canto se había convertido en lamento y mi baile en llanto.

Mis noches y mis días eran una escena de continuo dolor;
pero no dejé que nadie supiera la condición de mi mente.
Mi esposo utilizó todos los medios que estaban en su poder para distraerme de mi melancolía,
pero todo fue en vano.
La herida era muy profunda,
como para que pudiera ser sanada por algo menos que el "`bálsamo de Galaad.`"^
footnote:[Jeremías 8:22; 46:11]
Por temor a los malos espíritus, no me atrevía, ni mi esposo me permitía,
pasar mucho tiempo sola; y si tomaba la Biblia, él me la arrebataba diciendo:
"`¡Cómo has cambiado!
Antes me resultabas una compañía agradable, pero ahora no tengo consuelo en ti.`"
Me esforcé por soportar todo esto con paciencia,
creyendo que pronto tendría que soportar más de lo que el hombre podía infligir.

Fui donde el sacerdote para ver si podía aliviar mi condición;
pero era un desconocedor de mi estado.
Me aconsejó que tomara el sacramento y me entretuviera con pasatiempos inocentes.
Incluso me prestó un libro de oraciones, que según él era adecuado para mi condición;
pero todo esto fue en vano.
En cuanto a los pasatiempos, en ese momento se sentían como una carga;
en cuanto al sacramento, me consideré en un estado poco apto para recibirlo;
en relación con las oraciones,
me pareció que si en algún momento era capaz de orar apropiadamente,
lo lograría sin la ayuda de un libro.
Con el fin de aliviar mi dolor,
mi esposo me persuadió a que fuera a presenciar la demolición de un edificio,
donde también se había reunido un grupo de personas;
sin embargo tuvo un efecto contrario en mí. Mientras estaba allí,
un oficial llegó a convocar un jurado para el caso de un hombre que se había ahorcado,
y al recibir esta información,
me pareció escuchar una voz dentro de mí que se dirigía de esta manera:
"`Tú serás las siguiente en tener un final similar;
porque no eres digna de tener una muerte natural.`"

Durante dos meses fui tentada diariamente a atentar contra mi vida,
algunas veces tan fuertemente que apenas podía resistirme.
Antes de atreverme a caminar sola,
dejaba cualquier artículo que en un momento de descuido, pudiera usar para ese propósito;
deseando fervientemente al mismo tiempo que Dios
me preservara de quitarme la vida que me había dado,
y que Él habría hecho feliz, si hubiera aceptado Sus promesas de gracia,
de haber tomado en cuenta las convicciones con las
que Él me había favorecido desde mi juventud.
Durante toda esta amargura de espíritu, no pude derramar ni una lágrima.
Mi corazón se encontraba endurecido y mi vida era miserable;
pero Dios en su infinita misericordia, libró mi alma de esta esclavitud.
Una noche, estando en la cama lamentando mi condición, clamé: "`Oh mi Dios, te ruego,
en Tu misericordia, mírame por amor a Cristo,
quien ha prometido que toda clase de pecados y blasfemias serán perdonadas.
Señor, si te place en tu gracia extender esta promesa hacia mí, una criatura indigna,
que tiembla ante Ti, te obedeceré en todo lo que me ordenes.`"
Mi corazón fue suavizado en un instante y fui consumida en un mar de lágrimas.
Aborrecí mis ofensas pasadas y admiré las misericordias de mi Dios.
Ahora podía esperar en Cristo mi Redentor y contemplarlo con un ojo de fe.
Comprobé lo que había creído cuando el sacerdote me prestó su libro, es decir,
que cuando mis oraciones fueran aceptables, no necesitaría un libro.
Entonces tomé el sacramento y puedo decir que lo hice en reverencia y temor.

Liberada así de mi profunda angustia, parecía otra criatura,
y entonces caminaba a menudo sola y sin temor.
Una vez, mientras me aborrecía con gran humildad de espíritu,
me pareció escuchar una voz bondadosa, llena de amor, que me dijo: "`Nunca te abandonaré;
solamente obedéceme en todo lo que te dé a conocer.`"
Le respondí: "`Mi alma magnifica al Dios de misericordia.
Si Tú me concedes Tu gracia, dedicaré el resto de mis días a servirte.
Y si es Tu voluntad que mendigue mi pan,
me someteré con contentamiento a Tu providencia.`"

Entonces comencé a pensar en mis parientes de Pennsylvania,
a los cuales no había visto aún. Mi esposo me permitió ir a visitarlos,
y obtuve un certificado de parte del sacerdote, para que si me quedaba por un tiempo,
me recibieran como un miembro de la iglesia dondequiera que fuera.
Mi esposo me acompañó al transbordador "`Blazing-star,`"
se aseguró de que cruzara el agua sin problemas,
y luego regresó a casa.
De camino me caí de mi caballo y fui incapaz de viajar por
varios días. Me alojé en la casa de un honrado holandés,
quien, junto con su esposa,
me brindaron la mejor atención y no quisieron recibir ninguna recompensa por la molestia.
Los dejé sintiendo una profunda gratitud por su extraordinaria bondad,
y me dijeron que si alguna vez volvía por ese camino, debía alojarme con ellos.
Menciono esto, porque tendré la oportunidad de aludir a ello más adelante.

Cuando llegué al transbordador de Trenton,
me decepcioné grandemente al escuchar que todos mis parientes eran Cuáqueros,
y lo peor de todo era, que mi tía era una predicadora entre ellos.
Yo tenía muchos prejuicios contra este pueblo,
y a menudo me preguntaba cómo podían llamarse a sí mismos Cristianos.
Me arrepentí de haber viajado y estuve a punto de regresar; sin embargo,
como había avanzado tanto en mi viaje, proseguí,
aunque no esperé que mi visita fuera consoladora.
¡Jamás sospeché que me llevaría al conocimiento de la Verdad!

Fui de Trenton a Filadelfia por agua y de allí hasta donde mi tío a caballo.
Mi tío había muerto y mi tía se había casado de nuevo.
Sin embargo, tanto ella como su esposo me recibieron de la manera más cordial.
Apenas había estado tres horas en su casa cuando
mi opinión acerca de ellos empezó a cambiar.
Noté un libro sobre la mesa y como me gustaba leer, lo tomé. Mi tía me vio y me dijo:
"`Sobrina, ese es un libro de los Cuáqueros.`"
Ella vio que yo no era Cuáquera y supuso que no me gustaría. No le respondí,
sino que me pregunté: "`¿De qué escribirá esta gente?
He escuchado que ellos niegan las Escrituras y que
no tienen otra biblia sino el diario de George Fox,
y que además niegan las sagradas ordenanzas.`"
Pero, antes de haber leído dos páginas,
mi corazón ardía dentro de mí y por miedo a ser vista,
salí al jardín. Me senté y como el libro era corto,
lo leí por completo antes de regresar,
aunque a menudo me vi obligada a parar para dar rienda suelta a mis lágrimas.
La plenitud de mi corazón produjo este involuntario clamor: "`Oh mi Dios,
¿si llego al conocimiento de Tu verdad, debo ser de la opinión de este autor,
quien te ha buscado como lo he hecho yo?
¿Debo unirme a este pueblo, al que hace tan sólo unas horas prefería a los papistas?
Oh Dios de mi salvación y de mi vida,
que has manifestado abundantemente Tu paciencia y
tierna misericordia al redimirme del más bajo infierno,
te suplico que me dirijas por el camino correcto y me preserves del error.
Entonces cumpliré mi pacto,
y ¡estaré dispuesta a desprenderme de cualquier cosa por amor a Tu nombre!`"

Tras reponerme, me lavé la cara para que no notaran que había estado llorando.
Por la noche dormí muy poco,
porque el enemigo de la humanidad me persiguió con sus insinuaciones,
sugiriendo que yo era una de los que fluctuaban y no eran firmes en la fe.
Presentó varios versículos de la Escritura contra mí,
como ese '`en los postreros días habrá quienes engañarán aun a los escogidos,`'
y que esa era la clase de gente entre la que yo estaba,
y que yo me encontraba en peligro de ser engañada, etc.
Creyendo que había sido advertida de esta manera,
decidí cuidarme de estos engañadores y por algunas semanas no toqué ninguno de sus libros.
Al día siguiente, que era primer día de la semana,
quise ir a la iglesia que estaba a unos seis kilómetros de distancia,
pero al ser una extraña y no tener a nadie que me acompañara, desistí de la idea;
y viendo que la mayoría de la familia iba a su reunión, me fui con ellos.

Mientras estábamos sentados en silencio, eché un vistazo a la reunión y me dije:
"`¡Estas personas se sientan en silencio como unos tontos!
Sería mucho mejor que se quedaran en casa y leyeran la Biblia, o algún otro buen libro,
que venir hasta aquí a dormir.`"
En cuanto a mí, permanecí muy somnolienta, y al quedarme dormida,
casi me caigo de la banca.
Esta fue la última vez que me dormí en una reunión. Comencé entonces
a exaltarme con orgullo espiritual y a considerarme mejor que ellos,
pero esa disposición de mente no duró mucho.
Puede parecer extraño,
que tras haber vivido por tanto tiempo con alguien de esta sociedad en Dublín,
aún fuera una extraña para ellos.
Como respuesta, hay que tener en cuenta que mientras estuve allí,
nunca leí ninguno de sus libros, ni fui a una sola reunión. Además,
había escuchado tantos relatos de ellos que me hacían pensar,
que de todas las sociedades religiosas, ellos eran la peor.
Pero Aquel, que conocía la sinceridad de mi corazón,
miró mi debilidad con compasión. Pronto se me permitió ver mi error
y me fue mostrado que debía unirme a este pueblo.

Unas cuantas semanas después, hubo una reunión por la tarde en la casa de mi tío,
en la que estaba presente un ministro llamado William Hammans.
Yo tenía bastantes prejuicios contra él cuando se levantó, pero en seguida fui humillada,
pues él predicó el Evangelio con tanto poder que
me vi obligada a confesar que se trataba de la verdad.
Pero, aunque él fue el instrumento que me ayudó a salir de muchas dudas,
mi mente no había sido completamente librada de ellas
aún. Pues la mañana anterior a esa reunión,
había estado debatiendo con mi tío sobre el bautismo,
que también fue el tema abordado por ese ministro.
Y aunque su sermón eliminó todos mis escrúpulos sobre
ese punto más allá de cualquier objeción,
aún no me sentía dispuesta a creer que lo que había
escuchado procedía de la revelación divina,
y culpé a mis tíos de haberle hablado sobre mí al Amigo.
Sin embargo,
ellos me aclararon que desde que yo había llegado a su casa no lo habían visto,
hasta que entró a la reunión. Entonces, lo consideré como un mensajero de Dios para mí,
y dejando de lado mis prejuicios, abrí mi corazón para recibir la verdad.

Oh, la belleza de la verdad comenzó entonces a mostrarse ante mí,
junto con la gloria de todos los que continúan fieles a ella.
También vi cuán vacías estaban todas las sombras y los tipos, que,
aunque fueron muy adecuados en su día,
habían llegado a su fin por la venida del Hijo de Dios,
y la justicia eterna (que es una obra en el corazón) debía ser establecida en su lugar.
Se me permitió ver que todo lo que había atravesado
antes había sido para prepararme para ese día,
y que se acercaba el momento en que iba a ser requerido de mí ir y declararles
a otros lo que el Dios de misericordia había hecho por mi alma.
Me sorprendí tanto que quise ser librada de eso para no deshonrar
la Verdad y provocar que Su santo nombre fuera blasfemado,
pero no le di a conocer esas cosas a nadie.
De hecho, temía ser descubierta y ni siquiera tenía la apariencia de ser una Amiga.

Luego me contrataron para dirigir una escuela,
y al oír que había un puesto para mi esposo, le escribí y le pedí que se me uniera,
aunque no le di a conocer mi condición.

Me encantaba participar de las reuniones,
pero no me gustaba que me vieran yendo a ellas entre semana, y por tanto,
caminaba a la casa de reunión desde mi escuela a través del bosque.
A pesar de todo mi cuidado,
los vecinos que no eran Amigos enseguida comenzaron a injuriarme con el nombre de Cuáquera,
añadiendo que suponían que yo intentaba ser una tonta al convertirme en predicadora.
Así recibí el mismo reproche, que aproximadamente un año antes,
yo le había dado a una de las siervas del Señor en Boston.
Mi fe era tan débil que no podía soportar la humillación,
y con el fin de cambiar su opinión,
me vestía de manera más extravagante de lo que sentía libertad
de hacer incluso antes de haber conocido a los Amigos.
Continué bajo esta condición hasta que mi esposo llegó,
y entonces mi fe comenzó a ser probada.

Pero antes de llegar, él escuchó que me había convertido en Cuáquera,
ante lo cual zapateó y dijo: "`¡Preferiría haber oído que estaba muerta!
Porque aunque la amo, si esto es verdad, entonces todo mi consuelo se ha ido.`"
Después de cuatro meses sin verlo llegó donde yo estaba, y me levanté y le dije:
"`Querido, me alegro de verte.`"^
footnote:[En la década de 1600,
se puso de moda (como un medio para mostrar honor o adulación),
usar el "`usted`" o "`ustedes`" para dirigirse a las personas de mayor estatus social,
mientras que el "`tú`" y "`ti`" estaban reservados para sirvientes, niños,
o personas de baja posición social o económica.
Los primeros Amigos se apegaron a lo que entonces se consideraba "`lenguaje
simple,`" y usaban el "`tú`" y el "`ti`" con toda persona y sin distinción,
y el "`ustedes`" para dos o más.]
Al oír que me dirigí a él con este lenguaje sencillo, se encendió en cólera y exclamó:
"`¡El diablo tú, tú,
tú! ¡No me hables así!`" Me esforcé por todos los medios para tranquilizarlo,
y finalmente conseguí que estuviera en condiciones para hablar con mis parientes.
En cuanto nos quedamos solos, me dijo:
"`Veo que tus parientes Cuáqueros te han convertido en una.`"
Le respondí que no lo habían hecho, lo cual era cierto.
Él me dijo que no se quedaría entre ellos; y cuando encontró un lugar que le convenía,
consiguió trabajo y regresó enseguida a buscarme,
caminando en una tarde cuarenta y ocho kilómetros,
con el fin de evitar que yo asistiera a la reunión del siguiente día,
que era un primer día. Después de haber descansado,
al siguiente día me llevó al lugar de su trabajo y al apartamento
que había alquilado en la casa de un capellán de iglesia.
Este hombre era un enemigo despiadado de los Amigos,
y hacía todo lo posible por enfurecer a mi esposo contra ellos.

Aunque yo no me vestía como una Amiga, todos me consideraban una.
Cuando ese capellán y mi esposo se burlaban y me insultaban, me sentaba en silencio,
aunque de vez en cuando se me escapaba un suspiro involuntario, ante lo cual él decía:
"`¡Ves! ¿No te dije que tu esposa era una Cuáquera y que se convertiría en una predicadora?`"
En una de esas ocasiones,
mi esposo llegó donde yo estaba con gran furia y
agitando su mano sobre mi cabeza me dijo:
"`Sería mejor que te ahorcaran.`"
El horror se apoderó de mí,
y nuevamente me sumergí en una desesperación que continuó unos tres meses.
Tenía miedo de que si negaba al Señor,
los cielos se cerraran contra mí. Solía caminar mucho tiempo a solas por el bosque y ahí,
donde ningún ojo me podía ver, ni oído oír, lamentaba mi condición miserable.
A menudo deambulaba desde la mañana hasta la noche sin comer.
Me sentía tan abatida, que mi vida se convirtió en una carga para mí,
y el diablo parecía jactarse,
de que aunque los pecados de mi juventud habían sido perdonados,
ahora había cometido un pecado imperdonable y el infierno sería mi inevitable porción,
y que mis tormentos serían mayores que si me hubiera ahorcado al principio.

Por la noche no podía dormir, estando bajo esa dolorosa angustia de mente;
y si mi esposo me veía llorando, me denigraba por ello.
Al final, cuando él y su amigo percibieron que eran incapaces de persuadirme,
fue a ver al sacerdote en Chester para preguntarle qué podía hacer conmigo.
Este hombre sabía que yo era miembro de la iglesia de Inglaterra,
porque yo le había mostrado mi certificado.
Su consejo fue que me sacara de Pennsylvania,
y me llevara a algún lugar donde no hubiera Cuáqueros.
Mi esposo le respondió que a él no le importaba dónde fuéramos,
con tal de que pudiera restablecerme a mi usual espíritu entusiasta.
En cuanto a mí, no estaba dispuesta a oponerme a su propuesta,
ni me importaba dónde fuéramos.
De hecho,
nada me parecía esperanzador y diariamente esperaba
convertirme en una víctima de la ira Divina,
estando persuadida por la idea de que eso ocurriría por un rayo.

Cuando llegó el día de mudarnos, no me permitió despedirme de mis parientes;
y como mi esposo era pobre y no tenía caballo, me vi obligada a viajar a pie.
Llegamos a Wilmington, que estaba a unos veinticuatro kilómetros,
y de ahí hasta Filadelfia en barco.
Allí nos detuvimos en una posada,
donde me convertí en el espectáculo y en el tema de conversación de la gente.
Mi esposo les dijo que yo me había convertido en una Cuáquera y que tenía la intención,
si era posible, de buscar un lugar donde no hubiera ninguno.
Pensé para mis adentros: "`Una vez estuve en condiciones de merecer ese nombre,
pero ese tiempo ya pasó. ¡Ojalá pudiera, desde una verdadera esperanza,
volver a tener la oportunidad de confesar la verdad!
Aunque estuviera segura de recibir toda clase de crueldades, no las tomaría en cuenta.`"
Esos eran mis pensamientos, mientras él entretenía a la gente con mi historia,
en la que les decía que yo había sido una buena bailarina,
pero que en ese momento no podía hacerme bailar ni cantar.
Una de las personas se levantó y dijo: "`Traeré el violín,
y tendremos un lindo baile;`" una propuesta que agradó a mi esposo.
Cuando llevaron el violín, mi esposo se acercó y me dijo: "`Mi amor,
sacude esa tristeza y bailemos civilizadamente.
Solías bailar cuando eras una buena mujer de iglesia,
y eso es mucho mejor que ser una Cuáquera rígida.`"
Yo había tomado la decisión de no acceder a su petición,
fueran cuales fueran las consecuencias.
Le hice saber esto, aunque no me atreví a decirle mucho,
por miedo a su temperamento violento.

Entonces él me arrastró alrededor del lugar, hasta que se me salieron las lágrimas,
ante lo cual el músico paró y dijo: "`No tocaré más; ¡deja a tu esposa en paz!`"
Una persona de entre la gente, que había llegado de Freehold, al este de Jersey, dijo:
"`Veo que tu esposa es Cuáquera, pero si aceptas mi consejo,
no necesitas ir tan lejos como te propones.
Ven a vivir con nosotros; pronto la curaremos de su Cuaquerismo, además,
necesitamos a un maestro y a una maestra.`"
Mi esposo accedió y el cambio fue muy agradable para mí, como se verá a continuación.

Me fue concedida la recompensa de paz por haberme negado a bailar;
y entonces me regocijé más que si me hubieran hecho dueña de grandes riquezas.
Así que con lágrimas oré: "`Señor, temo pedir, y sin embargo,
sin Tu misericordioso perdón, soy miserable.
Por lo tanto, me postro ante Tu trono, implorando misericordia de Tu mano.
Oh Señor, te pido una vez más, prueba mi obediencia,
y entonces te obedeceré en lo que sea que ordenes,
y no temeré confesarte delante de los hombres.`"
Mis clamores fueron escuchados,
y me fue mostrado que "`el Señor no se complace en la muerte
del impío.`" Mi alma fue puesta en libertad una vez más,
y fui capaz de alabarlo.

De camino a Freehold,
visitamos al amable holandés que mencioné anteriormente en esta narración.
Nos dio la bienvenida y nos invitó a quedarnos un día o dos con él. Durante
nuestra estancia fuimos a una gran reunión de Presbiterianos,
en la que también se llevaba a cabo un juicio contra uno
de sus sacerdotes que había sido acusado de ebriedad.
Percibí tantas divisiones entre el pueblo con respecto a quién debía ser su pastor,
que sentí lástima por ellos.
Algunos insistían en que se restituyera al antiguo transgresor;
otros deseaban nombrar a un joven que había estado a prueba por unas semanas;
otros querían que se solicitara a Nueva Inglaterra un nuevo ministro.
Como respuesta a esa sugerencia, un hombre se dirigió al orador principal y dijo:
"`Señor,
cuando hayamos pagado el gasto (que no será pequeño)
de traer a este caballero de Nueva Inglaterra,
quizás no se quede con nosotros.`"
"`¿No sabes cómo hacer que se quede?`"
dijo otro.
"`Te diré;
solamente dale un gran salario y ciertamente se quedará.`" Escuché con atención el debate,
y me pareció claramente que esos predicadores mercenarios
eran movidos por una única razón,
que no era la consideración de las almas, sino el amor al dinero.
Yo conocía a uno de esos hombres,
al que llamaban "`reverendo divino,`" y al que esta gente casi adoraba,
quien había dejado a su rebaño en Long Island y se había
mudado a Filadelfia con el fin de obtener más dinero.
Yo misma había escuchado a algunos en la isla decir,
que casi se habían empobrecido en sus intentos por mantenerlo allí;
pero como no habían sido capaces de igualar lo que se le ofrecía en Filadelfia,
los había dejado.
Sin duda alguna,
esos son los pastores que están más interesados en el vellón que
en el rebaño. Y aunque digan que son los embajadores de Cristo,
sus bocas están llenas de mentiras, pues Su mandato es: "`De gracia recibisteis,
dad de gracia.`"

De camino a Freehold, llegando a Stony Brook,
mi esposo se volvió hacia mí y me dijo burlonamente:
"`Aquí está una de las sinagogas de satanás; ni te atrevas a correr a ella.
Espero verte curada de tu nueva religión.`" Un poco más adelante
llegamos a un gran arroyo sobre el que no había puente,
y al ser extraños en la zona no conocíamos ninguna forma de evitar atravesarlo.
Él cargó con nuestra ropa, que llevábamos en bultos,
y yo me quité mis zapatos y caminé por el agua en calcetines.
Era el duodécimo mes; el clima estaba muy frío y había nieve en el suelo,
pero el anhelo de mi corazón era que el Señor me santificara de
todas mis aflicciones y que me diera paciencia para soportarlas.

Tras haber caminado un poco más de un kilómetro,
llegamos a una casa que resultó ser una especie de taberna.
Mi esposo ordenó licor y yo tomé un poco de cidra caliente, que me hizo sentir muy mal;
así que, después de haber caminado un poco más allá de la casa,
me sentí muy débil como para seguir y me desmayé. "`¿Qué pasa ahora?`"
dijo mi esposo.
"`¿Qué, estás borracha?
¿Dónde está tu religión ahora?`"
Él sabía que no estaba borracha, y creo que en ese momento se compadeció de mí,
a pesar de la manera en que me habló. Después de recuperarme un poco,
continuamos y llegamos a otra posada en donde nos alojamos.

Al día siguiente, mientras viajábamos,
nos adelantó un joven que conducía una carreta vacía. Le preguntamos
si podíamos viajar con él y accedió de buena gana.
Hubo un tiempo en el que no me habrían visto montada en una carreta,
pero mi orgulloso corazón estaba ahora humillado y no me importaban las apariencias.
Esta carreta pertenecía a un hombre en Shrewsbury y se dirigía al lugar de nuestro destino.
Debido a que el conductor fue incapaz de llevar a cabo su comisión,
nos quedamos al cuidado de la carreta y de los caballos, y llegamos con ellos a Freehold.
Mi esposo hubiera preferido que yo me quedara allí
mientras él iba a dejar los caballos a salvo a casa;
pero yo le dije que no, que ya que me había llevado por todo el país como una vagabunda,
y que no me iba a quedar esperándolo.
Entonces fuimos juntos, y esa noche nos alojamos en la casa del dueño de la carreta.

Al siguiente día, en nuestro regreso a Freehold,
nos encontramos con un hombre que le dijo a mi esposo: "`Señor, ¿eres maestro?`"
Él le respondió: "`Sí.`" El extraño contestó:
"`He venido a contarle de dos escuelas nuevas, a tres kilómetros de distancia,
que necesitan un maestro.`"
Nunca supe cómo llegó a oír de nosotros esta persona
pues justo habíamos llegado la noche anterior.
Y me alegré de que no fuera un Cuáquero,
para que mi esposo no pensara que se trataba de una
conspiración. Me volví a él y le dije:
"`Querido, mírame con compasión, si es que aún te queda algo de amor hacia mí,
que espero que así sea, pues no soy consciente de haber hecho nada para perderlo.
Esta es una oportunidad para estabilizarnos,
y estoy dispuesta a hacer todo en mi poder para conseguir un medio de vida honrado.`"
Después de una corta pausa, accedió ir con el joven.
Por el camino, llegamos a la casa de un valioso Amigo que era un predicador,
aunque no lo sabíamos entonces.
Me sorprendió ver a la gente comportarse tan amablemente con nosotros.
No habíamos pasado mucho tiempo en la casa cuando fuimos invitados a pasar la noche allí,
ya que era el último día de la semana.

Mi esposo aceptó la invitación y dijo:
"`Mi esposa ha tenido un viaje agotador y me da mucha lástima.`"
Estas amables expresiones me afectaron, pues las había oído muy pocas veces.
La amabilidad del Amigo no podía haber provenido de mi apariencia de Cuáquera,
pues todavía no había cambiado mi forma de vestir.
La mujer de la casa, después de que decidimos quedarnos, fijó su mirada en mí y me dijo:
"`Me parece que te has enfrentado con muchos problemas,`" ante lo cual respondí muy poco.
Mi esposo,
observando entonces que ellos eran del tipo de personas
que tanto se había esforzado por evitar,
no nos dio oportunidad de hablar esa noche, pero a la mañana siguiente,
le di a conocer a esta amable dama un poco de mi situación.

Cuando llegó la hora de su reunión, yo deseaba ir,
pero no me atreví a pedirle permiso a mi esposo.
Mientras los Amigos se estaban alistando, le preguntaron si él los acompañaría,
mencionando que conocían a los que iban a ser sus patrones,
y que si estaban en la reunión, hablarían con ellos.
Él consintió en ir, entonces la Amiga le dijo: "`¿Y dejarás a tu esposa ir contigo?`"
Él rechazó esta petición; pero ella respondió a sus objeciones con tanta prudencia,
que él no pudo enfadarse, y finalmente consintió. Fui con alegría,
y fue una reunión celestial.
Mi espíritu se regocijó en el Dios de mi salvación. Que siempre pueda, con humildad,
conservar el recuerdo de Sus tiernas misericordias hacia mí.

Al final de la semana nos instalamos en nuestro nuevo lugar.
Nos alojamos en una habitación en la casa de un Amigo,
a un kilómetro y medio de cada escuela,
y a 13 kilómetros de la casa de reunión. Entonces consideré oportuno
hacerle ver a mi esposo que estaba decidida a unirme a los Amigos.
Cuando llegó el primer día, me dirigí a él de esta manera: "`Querido,
¿estás dispuesto a dejarme ir a la reunión?`" Él se enfureció y respondió: "`¡No,
no irás!`" Con firmeza le dije: "`Como esposa responsable,
estoy dispuesta a obedecer todas tus órdenes lícitas;
pero cuando tus órdenes se impongan sobre mi consciencia, no podré obedecerlas.
Ya me he equivocado al haberlo hecho demasiado tiempo.
Aunque eres cercano para mí, y como debe ser con una esposa, te amo; sin embargo, Dios,
que es más cercano para mí que el mundo entero,
me ha persuadido de que este es el camino por el cual debo andar.`"
Luego añadí: "`Esta no es una pequeña cruz para mi propia voluntad;
pero he entregado mi corazón y confío que Aquel que me ha pedido este acto de obediencia,
me permitirá mantenerme firmemente dedicada a Su servicio por el resto de mi vida,
y espero no ser una esposa peor por este motivo`". Mis palabras,
sin embargo, fueron inútiles, pues él continuó con una postura inflexible.
Pero como en ese momento había puesto mi mano en el arado y había decidido no retroceder,
me fui sin su permiso.
Yo pensé que me iba a seguir inmediatamente y que me obligaría a regresar,
pero no lo hizo.
Me detuve en la casa de uno de mis vecinos,
y después de pedirle a una niña que me mostrara el camino,
seguí regocijándome y alabando a Dios en mi corazón.

Así fue por un tiempo, tenía que caminar 13 kilómetros para ir a las reuniones,
lo que nunca me pareció difícil.
En ese entonces mi esposo tenía un caballo, pero no me permitía montarlo;
y cuando mis zapatos estaban gastados, no me dejaba tener un par nuevo.
Pero aunque él esperaba de este modo impedirme ir a las reuniones,
nada me lo impidió. Entonces amarraba mis zapatos
con mecates para mantenerlos en mis pies.

Y como todos los medios que utilizó no pudieron cambiar mi decisión,
me golpeó varias veces con severidad.
Me esforcé por soportar todo con paciencia,
creyendo que llegaría el tiempo cuando finalmente él se
daría cuenta de que yo tenía razón. Una vez se me acercó,
sacó su navaja y dijo: "`Si mañana vas a la reunión, te dejaré lisiada con esta navaja,
porque no te convertirás en Cuáquera.`"
No le respondí nada.
Por la mañana me dispuse a ir como de costumbre, y él no intentó hacerme daño.

Habiendo perdido la esperanza de recuperarme él mismo,
recurrió a un sacerdote en busca de ayuda,
a quien le dijo que yo había sido una mujer muy religiosa
en la forma de la iglesia de Inglaterra,
de la cual yo era miembro y tenía un buen certificado de Long Island,
pero que había sido hechizada y me había vuelto Cuáquera,
algo que casi le había roto el corazón. Por lo tanto, le solicitó a ese sacerdote,
como alguien que tenía cuidado de las almas,
que fuera a visitarme y se esforzara por sacarme del error,
lo que esperaba que con la bendición de Dios, se hiciera.
El sacerdote accedió y establecieron una fecha para su llegada,
la cual sería en dos semanas a partir de ese día, ya que dijo que no podía ser antes.
Mi esposo regresó a casa extremadamente complacido, y me contó lo que había sucedido.
Con una sonrisa le dije que yo confiaba en poder presentarle
defensa de la esperanza que había en mí,
aunque al mismo tiempo pensé, que el sacerdote no se iba a molestar por mí,
lo que resultó ser el caso.

Antes de que llegara el día señalado,
me fue requerido que confesara al mundo de manera más pública lo que yo era.
Sentí que se requería de mí que orara públicamente
en nuestra reunión. Temblé ante la idea,
y hubiera estado dispuesta a entregar mi vida con tal de ser excusada.
Y lo que hacía que esto me pareciera aún más difícil,
era que todavía no había sido aceptada como un miembro de la Sociedad,
pues me había abstenido de solicitar la membresía por temor
a que pudiera traer un escándalo a los Amigos.
Le rogué al Señor que me excusara hasta que me hubiera unido a ellos,
y que luego me entregaría voluntariamente.
Pero Su respuesta hacia mí fue: "`Yo soy un Dios que guarda el pacto,
y la palabra que te dije cuando te encontré en angustia,
que nunca te abandonaría si eras obediente a todo lo que te diera a conocer,
la cumpliré con certeza.
Si te niegas, Mi Espíritu no contenderá contigo para siempre.
No temas, yo te daré una salida para todas tus dificultades,
que serán muchas por amor a Mi nombre.
Sé fiel, y te daré la corona de vida.`"
En respuesta a estas palabras, le dije: "`Que se haga Tú voluntad, oh Dios.
Estoy en Tus manos, haz conmigo según Tu palabra.`"
Luego me arrodillé y oré en la reunión.

Ese día, como de costumbre, había ido a la reunión a pie.
Mientras mi esposo (como me lo hizo saber después) estaba acostado en la cama,
estas palabras cruzaron por su mente: "`¿Señor,
a dónde huiré para escapar de Ti?`" En ese momento se levantó,
y al ver que estaba lloviendo, fue por el caballo y salió a buscarme,
llegando justo cuando la reunión terminaba.
Me monté en el caballo tan rápido como pude,
para que no se enterara de que había hablado en la reunión. Sin embargo,
se enteró de ello, y tan pronto llegamos al bosque comenzó a decir:
"`¿Por qué buscas hacer mi vida infeliz?
¿No podrías ser una Cuáquera, sin convertirte también en una tonta de esa manera?`"
Le respondí con lágrimas: "`Mi amor, mírame con piedad si es que te queda algo.
¿Acaso piensas que yo, en la flor de mi vida, soportaría todo lo que sabes,
y aún más de lo que ni siquiera tienes conocimiento,
si no sintiera que es mi deber hacerlo?`"
Estas palabras lo alcanzaron, y respondió: "`Pues bien, me rindo.
Veo que no servirá de nada esforzarse.
Si esto es de Dios, no podré destruirlo; pero si proviene de ti,
perecerá.`" Pude ver las lágrimas en sus ojos, ante las cuales me invadió la alegría,
y sentí que había empezado a cosechar los frutos de mi obediencia.
Pero mis pruebas aún no habían terminado.

Llegó el tiempo señalado para que el sacerdote me visitara, pero no apareció ninguno.
Mi esposo fue a buscarlo, pero él se negó a asistir, diciendo que estaba ocupado,
lo que disgustó tanto a mi esposo que nunca más volvió a ir a escucharlo,
y por un tiempo no asistió a ningún lugar de adoración.

Mi fe fue entonces atacada tan fuertemente de otra manera,
que todas mis pruebas pasadas se veían insignificantes en comparación con esa.
Dicha prueba me sobrevino inesperadamente,
al escuchar a una mujer hablar de un libro que había leído,
en donde se afirmaba que Cristo no era el Hijo de Dios.
Mientras hablaba, una voz dentro de mí parecía responder: "`Él no lo es.
Todo es una fantasía y una invención de los hombres.`"

Así, una vez más, fui llena de una inexpresable angustia,
que duró alrededor de tres semanas;
y nuevamente busqué lugares desolados donde pudiera clamar
al Señor. Durante ese tiempo pasé noches enteras sin dormir.
Pensaba que Dios me había abandonado,
pero no dejé de confiar en Él. Mantenía viva la esperanza,
de que Aquel que me había librado (por así decirlo)
de las garras del oso y de las fauces del león,
me libraría de igual manera y a su debido tiempo de esa tentación. En efecto,
al final esa fue mi bendita experiencia; y encontré la verdad de Sus palabras,
de que todas las cosas ayudan a bien a los que lo aman y le temen.
Pues esos ejercicios de pruebas severas fueron para
prepararme para futuros servicios en Su causa;
y he aprendido que es necesario que Sus ministros
experimenten muchos bautismos para muerte,
para que así sean más aptos para hablar a las condiciones de otros.

Esto ocurrió justo después de mi primera aparición en el ministerio,
y los Amigos no habían llegado aún a hablar conmigo sobre el hecho de unirme a la Sociedad.
No sabían muy bien qué hacer,
hasta que sentí de nuevo que era requerido de mí hablar en una reunión,
lo cual no había ocurrido durante algún tiempo.
Entonces la Reunión Mensual designó a cuatro Amigos para que me visitaran.
Se fueron muy satisfechos con nuestra conversación, y me uní a la Sociedad.
Mi esposo continuaba sin ir a ningún lugar de adoración. Un día me dijo:
"`Me gustaría ir a la reunión contigo, sólo que me temo que voy a escucharte predicar,
lo cual no puedo soportar.`"
No procuré persuadirlo.
Cuando llegó la hora de irme para la reunión, él tomó el caballo,
me puso detrás de él y nos fuimos.
Por varios meses, si me veía preparándome para levantarme a predicar, salía;
hasta que un día me levanté antes de que él se percatara, y entonces,
como admitió después, se quedó porque le daba vergüenza salir.

A partir de ese momento,
dejó esa práctica y nunca más me impidió ir a la reunión. Aunque no había tomado la cruz,
su juicio estaba convencido, y en ocasiones derretido en lágrimas, me decía:
"`Mi querida, he podido ver la belleza que hay en la Verdad,
y que has seguido el camino correcto, en el que ruego a Dios que te preserve.`"
Le dije que yo esperaba que Aquel que me había dado fuerzas,
hiciera lo mismo con él. "`Oh,`" dijo, "`no puedo soportar el reproche que tú llevas,
ser llamado traidor y convertirme en el hazmerreír del mundo.
Pero ya no te lo impediré.`" Eso lo consideré como un favor,
y conservaba un poco de esperanza de que mis oraciones por él fueran escuchadas.

Vivíamos en una casa pequeña solamente nosotros dos,
que si bien era pobre y teníamos poco que gastar
en ella (nuestra cama no era más que paja),
estaba verdaderamente contenta.
Los únicos deseos que tenía eran los de mi propia preservación
y ser bendecida con la conversión de mi esposo.
Él se involucró con un grupo de hombres que temía que se burlaran de él,
lo que efectivamente sucedió. Le preguntaban cuándo planeaba comenzar a predicar,
porque veían que tenía la intención de convertirse en Cuáquero,
y que parecía que amaba más a su esposa desde que se había convertido en una.
Ellos solían llegar a nuestra casa, y lo incitaban a que se sentara y bebiera con ellos,
a veces hasta el amanecer, mientras yo pasaba afligida en un establo.
En una ocasión, mientras estaba sentada en esa condición,
le escuché decir a esos hombres:
"`No puedo soportar por más tiempo afligir a mi pobre esposa de esta forma;
porque sea lo que sea que piensen de ella, yo sé que es una buena mujer.`"
Luego, llegó donde yo estaba y dijo: "`Entra mi amor, Dios te ha dado mucha paciencia.
Voy a ponerle fin a esta práctica.`"
Esa fue la última vez que ellos se sentaron por la noche.

Mi esposo sugirió entonces que si él vivía en algún lugar
donde no supieran que había sido tan duro con los Amigos,
podría ser mejor.
Me opuse a esto, pues temía que no fuera de beneficio para él. Con frecuencia,
en un estado quebrantado y afectuoso,
condenaba sus malos tratos hacia mí. Yo le respondía
que esperaba que hubieran sido para mi propio bien,
y por ende deseaba que no se angustiara por ello.
Según la medida de gracia recibida, hice lo que pude,
tanto con mi ejemplo como con mis principios por su bien.
Mi consejo fue que se quedara dónde estaba,
pues temía que flaqueara en sus buenos propósitos si se mudaba a otro pueblo.

Nada de lo que dije sirvió. Al oír de un trabajo en Bordentown, fue allí,
pero no calificó para el puesto.
Luego se fue para Mount Holly, donde nos establecimos.
En poco tiempo, cada uno de nosotros estaba en una buena escuela,
obtuvimos una casa bien amueblada, y nos podría haber ido muy bien.
Nada parecía faltar para completar mi felicidad, excepto la conversión de mi esposo,
que en seguida tuve razones para dudar que vería. Y,
desgraciadamente resultó tal como me lo temía,
pues se entregó mucho a la bebida y se volvió peor que antes.

El dolor fue de nuevo mi porción. Oraba pidiendo paciencia para soportar mis aflicciones,
y someterme a las dispensaciones de la Providencia.
No murmuré; ni recuerdo haber pronunciado nunca expresiones severas,
excepto en la siguiente ocasión. Mi esposo llegó a casa un poco ebrio,
estado en el que se volvía muy irritable, y al encontrarme trabajando junto a una vela,
la apagó, dándome al mismo tiempo un manotazo en la oreja, y dijo:
"`No te has ganado la luz.`"
Ante este trato poco amable, al que no estaba acostumbrada desde hacía dos años,
me enojé un poco, y le dije: "`Eres un hombre malo.`"
Entonces me golpeó de nuevo; pero para entonces mi enojo se había enfriado,
y recibí el golpe sin una sola palabra a cambio.
Esto también lo disgustó,
y continuó de una manera salvaje pronunciando expresiones tan desesperadas,
como que creía que él estaba predestinado a la condenación,
y que no le importaba cuán pronto lo matara Dios.
Dije muy poco, hasta que al final, en la amargura de mi alma, oré con estas palabras:
"`Dios, mira mis aflicciones, y líbrame de alguna manera u otra.`"
Mi oración fue concedida, pero de manera tal, que pensé que terminaría con mi vida.
Mi esposo se fue a Burlington, donde se embriagó,
y luego se enlistó como soldado raso para ir a Cuba, en el año de 1740.
Había bebido muchas copas amargas, pero esta parecía la más amarga de todas.
Me culpé por haber hecho semejante petición, por la que temía haber disgustado al Señor,
quien, con desagrado, me la había concedido para mi castigo.

Pero desde entonces he tenido motivos para creer
que recibió algún beneficio por ese acto precipitado;
pues en el ejército hizo lo que no pudo hacer en casa, es decir,
sufrió por el testimonio de la Verdad.
Cuando su tropa se había preparado para entrar en combate, se negó a luchar.
Como consecuencia fue azotado y llevado ante el general,
el cual le preguntó por qué se había enlistado en
el ejército si no estaba dispuesto a luchar.
"`Lo hice,`" dijo, "`en una borrachera, cuando el diablo sacó lo mejor de mí.
Pero ahora mi consciencia está convencida de que no debo luchar; y no lo haré,
sufra lo que sufra.
No tengo más que una sola vida, y la puedes tomar si así lo quieres,
porque nunca tomaré las armas.`"
Él se apegó a esa resolución, pero debido al cruel trato que le dieron como consecuencia,
quedó tan incapacitado, que el general lo envió al Hospital de Chelsea, cerca de Londres.
Nueve meses después murió en ese lugar, y yo espero que haya tenido un buen final.

Nunca pensé de él como el peor de los hombres.
Si él le hubiera permitido a la gracia que hiciera su perfecta obra,
yo habría sido feliz en la situación más humilde de la vida.
He tenido motivos para bendecir a Dios,
por haberme permitido cumplir con mi deber en la posición de esposa;
y ahora que soy viuda, me someto a Su voluntad.
Que aún pueda ser preservada por el brazo del Divino Poder,
y que nunca olvide las tiernas misericordias de mi Dios,
cuyo recuerdo a menudo inclina mi alma en humildad delante de Su trono.
"`Señor, ¿qué era yo, para que revelaras a mi alma el conocimiento de Tu verdad,
y para que hicieras tanto por alguien que merecía Tu desagrado?
Que tú, oh Dios, seas glorificado y que yo sea humillada.
Tus propias obras te alaban; y en verdad,
para el alma humilde todo lo amargo le es dulce.`"

[.asterism]
'''

__El esposo de Elizabeth llevaba dos o tres años de haberse
ausentado antes de que ella se enterara de su muerte.
Le dejó casi 80 libras de deuda, que por ley, ella no estaba en la obligación de pagar.
Sin embargo,
debido a que muchos acreedores se quejaron y dijeron que no habrían
confiado en su esposo si no hubiera sido por ella,
se comprometió a pagarles tan rápido como pudiera.
Se dedicó con empeño al negocio de la escuela,
y por este medio, junto con el de la costura, se mantuvo con solvencia.
Poco a poco fue pagando las deudas mencionadas anteriormente,
y casi las pagó todas durante su viudez,
aunque durante ese tiempo viajó mucho como ministra.__

__En el noveno mes de 1746, se casó de nuevo con Aaron Ashbridge, en Burlington,
West Jersey.
En el año 1753,
comprendiendo que le era requerido visitar las reuniones
de los Amigos en Inglaterra e Irlanda,
dejó su hogar con el consentimiento de su esposo,
y en conformidad y con la aprobación de los Amigos, y realizó una visita a esas naciones,
pero al final cayó con una peligrosa enfermedad en la ciudad de Cork.
El 7 del quinto mes de 1755, estando gravemente afligida por un dolor de cuerpo,
expresó su deseo de tener paciencia ante sus sufrimientos, diciendo:
"`¡Oh querida Bondad, concédeme paciencia hasta que llegue mi cambio, y entonces,
no me abandones, oh Señor de mi vida!`"
En otra ocasión, encontrándose con dolor extremo, clamó: "`Señor, mírame.
Que la paciencia, mi vieja compañera, no me abandone ahora.`"
En un momento dijo: "`Me he esforzado por vivir sin una voluntad propia,
y espero haber soportado mis aflicciones con un grado de templanza cristiana.`"
Habiéndose debilitado durante varios días,
partió de esta vida tranquilamente el 16 del quinto mes de 1755,
a la edad de cuarenta y dos años,
y fue sepultada en el cementerio de los Amigos en Ballybrunhill.__
